---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Luna Sare's academic CV using the package `vitae`

<!-- badges: start -->
<!-- badges: end -->

The goal of lunasare-cv-vitae is to hold the source files used to build Luna Sare's academic CV with the [`vitae`](https://pkg.mitchelloharawild.com/vitae/) R package.

### Steps I followed:



```{r, error=TRUE}
R -e 'rmarkdown::render("cv-hyndman/cv-hyndman.knit.md")'
```

Install required packages:

```{r, eval=FALSE}
install.packages('vitae')
install.packages('tinytex')
tinytex::install_tinytex()
install.packages("rorcid")
install.packages("scholar")
install.packages("magrittr")
library(magrittr)
```

Package versions:
```{r, eval=TRUE, warning=FALSE}
packages <- c("vitae", "tinytex", "rorcid", "scholar", "magrittr")
names(packages) <- packages

lapply(packages, utils::packageVersion)
```

Getting my education with ORCID

```{r, eval=TRUE}
orcid_data <- do.call("rbind",
  rorcid::orcid_educations("0000-0001-7668-2528")$`0000-0001-7668-2528`$`affiliation-group`$summaries
)
```
Getting my publications with Google;

```{r, eval=TRUE}
scholar::get_publications("rpXUk04AAAAJ") %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal,
    why = cites
  )
```
